web/doc_app/urls.py
# from django.contrib.auth.views import LoginView
from django.urls import path
from django.contrib.auth import views as auth_views


from . import views
from .views import LoginUser

urlpatterns = [
    path('', views.doc1_page, name = 'home'),
    # path('login', LoginUser.as_view(), name = 'login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('seccretary', views.secretery, name='secretary'),
    path('secсretary/create_documentik/<int:order_type>/<int:order_id>', views.make_doc_procces),
    path('secсretary/delete_orderik/<int:order_id>/', views.delete_order, name = 'secretary/delete_order'),
    path('doc1/process/', views.doc1_form_active, name = 'doc1_process'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('doc_app.urls')),
]

web/doc_app/models.py
from django.db import models

class Order(models.Model):
    doc_type = models.PositiveSmallIntegerField()
    surname = models.CharField(max_length=50, blank=False)
    name = models.CharField(max_length=50, blank=False)
    patronymic = models.CharField(max_length=50)
    grade_c = models.PositiveSmallIntegerField(blank=False)
    grade_b = models.CharField(max_length=5, blank=False)
    email = models.EmailField()
    status = models.BooleanField(default=0)


class Student(models.Model):
    id = models.IntegerField(primary_key=True)
    fio = models.CharField(max_length=150)

# class File(models.Model):
#     title = models.CharField(max_length=150)
#     file = models.FileField(upload_to='')
#
#     def __str__(self):
#         return self.title

web/doc_app/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.template.defaultfilters import default
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model


class Doc1_Form(forms.Form):

    Surname = forms.CharField(label='Фамилия',
            max_length=50, widget=forms.TextInput(attrs={'maxlength': '50'}))
    Name = forms.CharField(label= 'Имя',
            max_length=50, widget=forms.TextInput(attrs={'maxlength': '50'}))
    Patronymic = forms.CharField(label='Отчество',
            max_length=50, widget=forms.TextInput(attrs={'maxlength': '50'}), required=False)
    Grade_c = forms.ChoiceField(label='Класс (цифра)',
            choices=((None, None), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)), initial='')
    Grade_b = forms.ChoiceField(label='Класс (буква)',
            choices=((None, None), ("А", "А"), ("Б", "Б"), ("В", "В"), ("Г", "Г")), initial='')
    Email = forms.EmailField(label='Электронная почта', required=False)


User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


#     russian_letters_validator = RegexValidator(
#         r'^[А-Яа-яЁёs]+$',  # Разрешаем только русские буквы и пробелы
#         'Введите только русские буквы.'
#     )

# validators=[russian_letters_validator]

web/doc_app/views.py
from Tools.demo.mcast import receiver
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse, FileResponse
from django.urls import reverse
from .forms import Doc1_Form
from .db_funcs import get_order_db, get_all_orders_db, create_order_db, delete_order_db, update_order_status, chek_student, get_all_students
from .microsoft_world import make_doc
import os, datetime
from .models import Order, Student
from .send_email import send_notification


def doc1_page(request):
    userform = Doc1_Form()
    return render(request, "index.html", {"form": userform, "semi_title": "Справка об обучении в Лицее"})


def doc1_form_active(request):
    surname = request.POST.get('Surname')
    name = request.POST.get('Name')
    patronymic = request.POST.get('Patronymic')
    grade_c = request.POST.get('Grade_c')
    grade_b = request.POST.get('Grade_b')
    email = request.POST.get('Email')

    surname = surname.capitalize()
    name = name.capitalize()
    patronymic = patronymic.capitalize()

    print(surname, name, patronymic, grade_c, grade_b, email)
    print(os.listdir())

    check = chek_student(surname, name)
    print(check)


    # error_text = 'ошибка'
    # redirect_order = reverse('home')
    # return render(request, "order_error.html", {"error_text": error_text, "href": redirect_order})


    if check == True:
        create_order_db(doc_type=1, surname=surname, name=name, patronymic=patronymic, grade_c=grade_c, grade_b=grade_b, email=email)
        return render(request, 'order_success.html')
    else:
        return render(request, 'order_error.html')







@login_required
def secretery(request):
    orders_list = get_all_orders_db()
    # Заголовки таблицы
    orders = ('<tr>'
              '<th>№ Заявки</th>'
              '<th>Тип Справки</th>'
              '<th>Фамилия</th>'
              '<th>Имя</th>'
              '<th>Отчество</th>'
              '<th>Класс</th>'
              '<th>Статус заявки</th>'
              '<th colspan="2">Действия</th>'
              '</tr>')

    for i in orders_list:
        order_id = i.get('id')
        order_type = i.get('doc_type')
        order_surname = i.get('surname')
        order_name = i.get('name')
        order_patronymic = i.get('patronymic')
        order_grade = str(i.get('grade_c')) + i.get('grade_b')
        order_status = i.get('status')

        # если заявка ещё не обработана
        if not order_status:
            status_text = 'Не обработана'
            href = (
                f'<td><a class="btn-accept" href="secсretary/create_documentik/{order_type}/{order_id}">Принять</a></td>'
                f'<td>'
                f'<button type="button" class="reject-btn" '
                f'onclick="confirmAction(\'secсretary/delete_orderik/{order_id}\', '
                f'\'Отклонить заявку №{order_id}?\')">Отклонить</button>'
                f'</td>')
        else:
            status_text = 'Обработана'
            href = (
                f'<td>'
                f'</td>'
                f'<td>'
                f'<button type="button" class="delete-btn" '
                f'onclick="confirmAction(\'secсretary/delete_orderik/{order_id}\', '
                f'\'Удалить заявку №{order_id}?\')">Удалить</button>'
                f'</td>'
            )

        # строка таблицы
        order_tr = (f'<tr>'
                    f'<td>{order_id}</td>'
                    f'<td>{order_type}</td>'
                    f'<td>{order_surname}</td>'
                    f'<td>{order_name}</td>'
                    f'<td>{order_patronymic}</td>'
                    f'<td>{order_grade}</td>'
                    f'<td>{status_text}</td>'
                    f'{href}')

        orders += order_tr

    body_orders = f'<table align="center">{orders}</table>'
    return render(request, 'secretary.html', {"body_orders": body_orders})


@login_required
def make_doc_procces(request, order_type, order_id):
    order = get_order_db(order_id)
    name = order.get('name')
    surname = order.get('surname')
    patronymic = order.get('patronymic')
    grade_c = order.get('grade_c')
    grade_b = order.get('grade_b')
    email = order.get('email')

    make_doc(surname, name, patronymic, grade_c, grade_b)
    date_now = datetime.date.today()
    day = date_now.strftime('%d')
    month = date_now.strftime('%m')

    file_path = os.path.join('new_docs', f"new_{surname}_{name}_{day}_{month}.docx")
    response = FileResponse(open(file_path, 'rb'), as_attachment=True)

    update_order_status(order_id)

    send_notification(email, name, surname)

    return response


@login_required
def delete_order(request, order_id):
    delete_order_db(order_id)
    return render(request, 'delete_order.html',
                  {'order_number' : order_id})


class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = 'registration/login'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Авторизация")
        return dict(list(context.items()) + list(c_def.items()))

web/doc_app/templates/delete_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Удаление заявки</title>
</head>
<body>
<h1><p style="text-align: center;">Заявка № {{ order_number }} успешно удалена</p></h1>
</body>
</html>

web/doc_app/templates/index.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        <h1>Форма для справки</h1>
        <h2>{{ semi_title }}</h2>
        <form method="POST" action="doc1/process/">
            {% csrf_token %}

            <label for="id_Surname">Фамилия</label>
            {{ form.Surname }}

            <label for="id_Name">Имя</label>
            {{ form.Name }}

            <label for="id_Patronymic">Отчество</label>
            {{ form.Patronymic }}

            <div class="form-row">
                <div class="form-group">
                    <label for="id_Grade_c">Класс (цифра)</label>
                    {{ form.Grade_c }}
                </div>
                <div class="form-group">
                    <label for="id_Grade_b">Класс (буква)</label>
                    {{ form.Grade_b }}
                </div>
            </div>

            <label for="id_Email">Электронная почта</label>
            {{ form.Email }}

            <input type="submit" value="Отправить">
        </form>
    </div>
</body>
</html>

web/doc_app/templates/make_document.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Создание документа </title>
</head>
<body>
    <h1><p style="text-align: center;">Справка создана</p></h1>
</body>
</html>

web/doc_app/templates/order_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Acced denied :(</title>
</head>
<body>

</body>
</html>

web/doc_app/templates/order_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Запрос справки</title>
</head>
<body>
    <h1><p style="text-align: center;">Ваша заявка успешно подана</p></h1>
</body>
</html>

web/doc_app/templates/secretary.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Администратор</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/secretary.css' %}">
</head>
<body>
<h1><p style="text-align: center;">Администрирование системы</p></h1>
<h4 style="text-align: center;">Список всех заявок на справки:</h4>
{% autoescape off %}
{{ body_orders }}
{% endautoescape %}

<div id="confirmModal" class="modal">
  <div class="modal-content">
    <p id="modalText">Вы уверены?</p>
    <button class="ok-btn" id="okBtn">ОК</button>
    <button class="cancel-btn" id="cancelBtn">Отменить</button>
  </div>
</div>

<script>
  let currentActionUrl = null; // сюда сохраняем ссылку для действия

  function confirmAction(actionUrl, message) {
      currentActionUrl = actionUrl;
      document.getElementById("modalText").innerText = message;
      document.getElementById("confirmModal").style.display = "block";
  }

  document.getElementById("okBtn").addEventListener("click", function() {
      if (currentActionUrl) {
          // отправляем запрос на сервер
          fetch(currentActionUrl)
              .then(r => r.text())
              .then(data => {
                  alert("Операция выполнена!");
                  location.reload(); // обновим страницу, чтобы таблица обновилась
              });
      }
      document.getElementById("confirmModal").style.display = "none";
  });

  document.getElementById("cancelBtn").addEventListener("click", function() {
      document.getElementById("confirmModal").style.display = "none";
  });
</script>

</body>
</html>